# vim: ts=2 sw=2 smartindent

- name: Install syncoid service files
  ansible.builtin.template:
    src: syncoid.service.j2
    dest: "/etc/systemd/system/zfs-syncoid-{{ item.name }}.service"
  loop: "{{ syncoid }}"
  register: service

- name: Install syncoid timer files
  ansible.builtin.template:
    src: syncoid.timer.j2
    dest: "/etc/systemd/system/zfs-syncoid-{{ item.name }}.timer"
  loop: "{{ syncoid }}"
  register: timer

- name: Enable the timer files
  ansible.builtin.systemd:
    name: "zfs-syncoid-{{ item.name }}.timer"
    state: restarted
    enabled: yes
    daemon_reload: yes
  loop: "{{ syncoid }}"
  when: service.changed or timer.changed
