---
syncoid:
  - name: 'local'
    src: 'zroot'
    dest: 'zbackup/zroot'
    frequency: 'every 3 hours'
    timer: |
      OnBootSec=5min
      OnUnitActiveSec=3h

  - name: 'remote'
    src: 'zbackup/zroot'
    dest: 'root@pandora:storage/ds2/backups/zroot'
    frequency: 'every 8 hours'
    timer: |
      OnBootSec=10min
      OnUnitActiveSec=8h
