# vim: ts=2 sw=2 smartindent

- name: Configure pacman
  include: pacman.yml
  become: yes

- name: Configure services
  include: services.yml
  become: yes

- name: Install scripts
  include: scripts.yml
