# vim: ts=2 sw=2 smartindent

- name: Add pacman repos
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/pacman.d/"
  with_fileglob:
    - "pacman.d/*"

- name: Copy pacman conf
  ansible.builtin.copy:
    src: pacman.conf
    dest: /etc/pacman.conf

- name: Import archzfs key
  community.general.pacman_key:
    id: DDF7DB817396A49B2A2723F7403BD972F75D9D76
    url: https://archzfs.com/archzfs.gpg
    state: present

- name: Run pacman -Syu
  community.general.pacman:
    update_cache: yes
    upgrade: yes

- name: Remove potentially conflicting packages
  community.general.pacman:
    name: "{{ conflicting_packages }}"
    state: absent

- name: Install packages
  community.general.pacman:
    name: "{{ packages }}"
    state: present
