# vim: ts=2 sw=2 smartindent

- name: Enable and start podman systemd socket
  ansible.builtin.systemd:
    name: podman.socket
    state: started
    enabled: yes
  become: yes

- name: Enable and start podman user socket
  ansible.builtin.systemd:
    name: podman.socket
    state: started
    enabled: yes
    scope: user

- name: Enable and start plocate timer
  ansible.builtin.systemd:
    name: plocate-updatedb.timer
    state: started
    enabled: yes
  become: yes

- name: Enable and start pkgfile update timer
  ansible.builtin.systemd:
    name: pkgfile-update.timer
    state: started
    enabled: yes
  become: yes
