# vim: ts=2 sw=2 smartindent

- name: Enable and start podman systemd socket
  ansible.builtin.systemd:
    name: podman.socket
    state: started
    enabled: yes

- name: Enable and start podman user socket
  ansible.builtin.systemd:
    name: podman.socket
    state: started
    enabled: yes
    scope: user
  become: no

- name: See if apparmor exists
  ansible.builtin.stat:
    path: /usr/bin/aa-status
  register: aa

- name: Install apparmor profiles
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/apparmor.d/local/"
    mode: '0644'
  with_fileglob:
    - "apparmor.d/*"
  when: aa.stat.exists
  register: aa_profiles

- name: Reload apparmor profiles
  ansible.builtin.shell:
    cmd: "apparmor_parser -r /etc/apparmor.d/{{ item | basename }}"
  with_fileglob:
    - "apparmor.d/*"
  when: aa_profiles.changed

- name: Enable and start plocate timer
  ansible.builtin.systemd:
    name: plocate-updatedb.timer
    state: started
    enabled: yes

- name: Enable and start pkgfile update timer
  ansible.builtin.systemd:
    name: pkgfile-update.timer
    state: started
    enabled: yes

- name: Install custom systemd services
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system/"
  with_fileglob:
    - "systemd/*"

- name: Enable timer files
  ansible.builtin.systemd:
    name: "{{ item | basename }}"
    state: started
    enabled: yes
    daemon_reload: yes
  with_fileglob:
    - "systemd/*.timer"

